printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: false
jsxBracketSameLine: false
arrowParens: always
proseWrap: always
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
